server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb+srv://kamilurbanik:B91T9MGSmzlQQo5K@fitnesscluster.zawqjy1.mongodb.net/?retryWrites=true&w=majority&appName=FitnessCluster
      database: fitness_recommendations

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}